title: Tim Searle
description: >-
  A personal preamble into the state of the technology industry, project statuses and obscure learnings from my journey as a software engineer.
baseurl: ""
url: "https://www.searle.dev"
twitter_username: timsearle_
github_username:  timsearle

# Build settings
theme: minima
plugins:
  - jekyll-feed

include: 
  - .well-known

exclude:
  - Gemfile
  - Gemfile.lock
