name: "Pull Request"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Verify Build"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read

    steps:
    - name: "Checkout ${{ github.ref }} from ${{ github.repository }}"
      uses: actions/checkout@v4

    - name: "Setup Ruby"
      uses: ruby/setup-ruby@v1.172.0
      with:
        bundler-cache: true

    - name: "Build Site with Jekyll"
      run: ./scripts/build.sh
      env:
        JEKYLL_ENV: production
        BASE_URL: ${{ steps.pages.outputs.base_path }}
